### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Nyaran** [Pistachitos/Sick-Beard#1]
This is not a issue, is for everyone can ask anything about project

**Comment by Diaoul** [comment]
That's really cool you took the time to make it work :)
I'm going to add a few fixes to subliminal soon, stay tuned

**Comment by zkvsky** [comment]
Wanted to thank you for this fork :)  It works very well for me now (after you squashed this video deleting bug during processing ;)
List view seems to be a bit heavy (and noticed that thumbs there use big posters image)
Cheers!
