### ISSUE TITLE
Sick-Beard hangs when auto-updating with the web UI

### ISSUE THREAD

**Issue by MartinAyla** [Pistachitos/Sick-Beard#10]
Hi (again) :)

When I choose to Update in the web UI, Sick-Beard hangs on "Shutting down Sick-Beard".

I have to kill the python process and start Sick-Beard again manually.

Ps. It does do the update! it's just the restarting that doesn't work, it seems.

Here is the command I start Sick-Beard with (on Mac OS X 10.8.2):

python SickBeard.py > /dev/null 2>&1 &

**Comment by Nyaran** [comment]
this still happens?

**Comment by MartinAyla** [comment]
Yes, it still happens, just tried it with the latest git updates, a couple of days ago (I have to quit the Python thread manually).

**Comment by rkuijpers** [comment]
It still happens, as I tried to update.
After isetz updated the code, I got an update notification in Sickbeard (Windows 7 x64, running python).

Got stuck on "shutting down sickbeard" but it did update. Had to start sickbeard.py manually after that, and then Sickbeard worked.

**Comment by isetz** [comment]
It happens to me also. Running SB in my Synology NAS. But in my case, SB works after the update, the only problem is the window doesn't refresh after the reboot.

**Comment by MartinAyla** [comment]
It doesn't happen for me anymore, I'm using latest git version :)

**Comment by Nyaran** [comment]
Nice, I don't know when was fixed hahaha :P
