### ISSUE TITLE
Windows Binary

### ISSUE THREAD

**Issue by fabioneves** [Pistachitos/Sick-Beard#13]
Hello,

Is it possible to release this in a windows binary? I'm interested in your fork because of the subtitle support.

Thanks!

**Comment by Nyaran** [comment]
I want to do that when I finish some stuff.
Anyway you can run SB on Windows associating py files to open with pythonw.exe (pythonw.exe don't show console window). Then run SickBeard.py

**Comment by fabioneves** [comment]
I just need to install python for windows and add it to PATH or do I need something else?

**Comment by Nyaran** [comment]
Just install python 2.6 or 2.7 and add it to PATH, yes.

**Comment by fabioneves** [comment]
then I create a .cmd or .bat for "python SickBeard.py", right?

**Comment by Nyaran** [comment]
Yes, you can run with a bat file, but better use pythonw insteadof python.
I don't use bat, as I say on first reply, I associate .py extension to be executed with pythonw.exe, then I only need to double click on SickBeard.py to start it :P

**Comment by fabioneves** [comment]
Ah ok. got it. Then I just need a shortcut to the 'SickBeard.py' file to start with my server. Thanks!
Are you merging with the "SickBeard Branch"?

**Comment by Nyaran** [comment]
Yes, I try to update it frequently.

**Comment by fabioneves** [comment]
Ok, perfect. I'm gonna use your fork. Thanks !

**Comment by fabioneves** [comment]
I've installed python 3.3 for windows. It won't work with this version? When I double click the .py script, nothing happens. I just see a console to appear and disappear.

**Comment by Nyaran** [comment]
Sick-Beard doesn't work with Python 3.3, use Python 2.6 or 2.7 http://www.python.org/ftp/python/2.7.3/python-2.7.3.msi

**Comment by fabioneves** [comment]
Sorry to bother you again Nyaran. I've installed Python 2.7.3, added python directory to the Path env var of windows but when I click SickBeard.py (open with pythonw.exe) I see a console open/close and nothing else happens. Do you have any idea of it might be? Do I need to run setup.py before or something else?

**Comment by fabioneves** [comment]
Hmmm.. looks like I need something more

d:\sickbeard>python setup.py
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import py2exe, sys, os, shutil, datetime, zipfile, subprocess, fnmatch
ImportError: No module named py2exe

d:\sickbeard>python SickBeard.py
The Python module Cheetah is required

d:\sickbeard>

**Comment by Nyaran** [comment]
setup.py is old and don't works now.

I forget that you need to install Cheetah
Download this file and save it in python folder (probably C:\Python27) http://peak.telecommunity.com/dist/ez_setup.py
On command line write:
cd C:\Python27
python ez_setup.py Cheetah

When finish, try to run SickBeard again

**Comment by fabioneves** [comment]
Worked fine, thanks!
What's being used for the subtitles? Subliminal? I wanted to add a new source for the subtitles, I've seen "legendas.tv" support in subliminal repo.

**Comment by Nyaran** [comment]
Yes, subliminal was integrated into SickBeard for subtitles management.

**Comment by fabioneves** [comment]
How hard it is to add a subtitle source that's for subliminal?

**Comment by Nyaran** [comment]
That's depends your python programming skills.
Look the code of other services to take an example.

**Comment by fabioneves** [comment]
Yeah, but I meant, imagine I have already the source coded. Do I just put it on the subliminal folder where the other ".py" files of the other sources are? Will it appear in Sick Beard?

**Comment by Nyaran** [comment]
Just put the file in subliminal/services folder and add a new element to SERVICES array in core.py

**Comment by DisasteR** [comment]
Why not submit your provider to be included to this fork :)
