### ISSUE TITLE
Add NZBX support please?

### ISSUE THREAD

**Issue by rkuijpers** [Pistachitos/Sick-Beard#14]
Could you please consider adding working NZBX support (https://nzbx.co/api)?
I've seen forks with working NZBX support, but to be honest I like your fork, only this is what I'm missing at the moment.

A few other forks work with NZBX, maybe it's possible to merge the code into yours?
I'm very new to GitHub, so forgive me if this isn't the way to ask for this... ;)
I already saw others having problems with NZBX, but these devs got it working I believe:

https://github.com/LemonadeDev/SickBeard
https://github.com/schumi2004/Sick-Beard
https://github.com/ibawt/SickBeard
https://github.com/orther/SickBeard/commit/4ae51e7a82ad1bb5825880d35747e1b7f93c6a06

I've read a few things about adding NZBX support manually, but to be honest I'm already very glad I got your version working on Win 7 x64. 
I must say, great job, your version of SB works great for me!

**Comment by Nyaran** [comment]
I can try to add it, but I don't use nzb for download, then I can't test it correctly.

**Comment by DisasteR** [comment]
simply get sickbeard/providers/nzbx.py file from LemonadeDev/SickBeard
put it int same place.

add nzbx to sickbeard/**init**.py providers import.
add nzbx to sickbeard/providers/**init**.py providers array.

it maybe require some tweaking to work correctly (https://github.com/LemonadeDev/SickBeard/commit/7e8cd5a0cfd875f47f506db518e3f3cad29ab89e)
but dont think that touching the sickbeard core like that it's the better way.

**Comment by rkuijpers** [comment]
NZBX should be publicly available to try, as I tried Schumi2004s fork before, after using the official Windows version for some time. It immediately started to use NZBX, even when I didn't have a paid account there. 

I'll follow DisasteR's directions and try to make it work myself, but my skills are VERY minimal (until now).
I don't like fiddling in something that works perfectly well otherwise, especially when I don't yet understand how things work. But I'll try, what could go wrong, right? 

Thanks for considering adding NZBX support Nyaran!

**Comment by rkuijpers** [comment]
I have tried to add NZBX like DisasteR said, adding those files to Sickbeard, but pythonw.exe would start and immediately shut down.

As I said earlier, I have very limited knowledge about these things, the commit he refers to looks like witchcraft to me ;)

But as there has been important news on the NZBX front, maybe there is a reason now for adding NZBX support:
NZBX will work for all that will register there, not only for premium members! It's now free to use!

I've read reviews of users that only use NZBX as their search provider, and it looks like using this search provider alone (no others) already gives very good results.

So maybe this is enough reason to look into adding NZBX more closely?
There is also talk about it being added to the next official Sickbeard update, but I don't know about that one.

Hope adding NZBX support is still on todo your list Nyaran! Thanks!

The downloading/moving of subtitles with the episodes is working perfectly now (my other "issue" you looked into). Thanks!

**Comment by rkuijpers** [comment]
Nyaran, NZBX is working since you added support for it, thanks!
