### ISSUE TITLE
Subtitles filename

### ISSUE THREAD

**Issue by interpeix** [Pistachitos/Sick-Beard#15]
Is there anyway to modify how the subtitle files are named?. 
For example:
If I have this video filename Example1.avi, the subtitle download on the same path(that is correct) and the name of the subtitle file is Example1.es.srt (.es is the language of the sub). I want to remove the ".es"

Thank you in advance.

**Comment by Nyaran** [comment]
No, ".es" tag is necessary. Without it SB doesn't know what language is that subtitle.
Most of the players can open subtitles with language tag without problems.

**Comment by isetz** [comment]
Subliminal adds the language code automatically to the downloaded subtitle file when "multi" option is enabled and, as Nyaran has already said, it is mandatory that this is enabled as it is.

**Comment by interpeix** [comment]
Thank you so much for your comments. :+1:
