### ISSUE TITLE
Add option to move subtitles together or after episodes have been moved by Sickbeard

### ISSUE THREAD

**Issue by rkuijpers** [Pistachitos/Sick-Beard#17]
Hi again,

I'm using your Sickbeard version on my pc running Windows 7 x64 with much pleasure, although I do have a request:

Whenever Sickbeard downloads an episode, it puts it in the temorary download folder on my pc. (Sickbeard afterwards processes it and moves it to the final folder on my NAS.) So far everything is perfect!

The built-in Subliminal downloads a subtitle for the same episode, and puts it in the same temporary download folder of the episode on my pc.

sabToSickBeard moves the episode and .nfo to the final folder on my NAS, but doesn't touch the subtitle(s) that were downloaded with it. The subtitles stay in the temporary download folder on my pc.

I guess this is due to the fact Sickbeard processes all files with the EXACT same name, while the built-in Subliminal downloads the subtitles with .en and .nl in the filename of the srt.file.

The option:  

"Move Associated Files Move srr/srt/sfv/etc files with the episode when processed?   NOTE: .nfo will be renamed to .nfo-orig when moved." 

doesn't work for the subs that are downloaded by the built-in Subliminal.

The downloaded .en and .nl subs stay in the temporary download folder on my pc!
They have to be moved manually to the final folder on my NAS where the episode is moved to.

Is it possible for you to alter the "Move Associated Files" to also include subtitles with language names like .en and .nl in it? That would be the simplest solution I think?

Or let Subliminal download the subtitles after the downloaded episode has been processed and moved to the final folder on my NAS?

Or maybe let an extra piece of script take care of this, in sabToSickBeard?

As a workaround I let Sickbeard redownload the subtitles after the episodes have been moved to to the final folder, but it must be possible to let Sickbeard take care of the moving of subtitles automatically?

I hope you can fix this, as it happens a lot that when I want to view an episode in my livingroom, I have to go upstairs to my computer, and manually move the subtitles to the right final folder of the serie. That isn't a big problem if you have to do it for one or a few episodes, but it's a lot of work when you have to do it for a complete season or multiple series.

It beats the purpose of having an automated download system, if you have to manually move the downloaded subtitles every time, right?

Thanks in advance for reading this, might be I'm the only one having this issue(?), as I would have thought others would have mentioned this before. Have been searching Google for answers, but can only find workarounds and scripts for Sickbeard on NAS.
My NAS unfortunately can't run Sickbeard, and I like having it on my pc!

**Comment by isetz** [comment]
Hi! We'll look into it. I don't think fixing the "move associated files" option should be much trouble. But I don't understand quite well why your subtitles are downloaded before SB moves the files, in my case subtitles are always downloaded inside the destination folder of the show, after the postprocessing.

**Comment by isetz** [comment]
Ok, my mistake. What happens is that the subtitles are moved in my case without problems. So I guess it must be some issue with the sabToSickBeard script.

**Comment by rkuijpers** [comment]
Do you use multiple languages in subtitle downloads?
In that case for downloaded subtitles in English, .en is added to the name of the subtitle.
Same goes for Dutch subtitles, .nl is added.

Both aren't moved by Sickbeard. Seems that's normal, as Sickbeard only looks to move files with the exact same filename. The subtitles have been renamed by the built-in Subliminal, so the name isn't exactly the same name as the episode anymore.

Do subtitles with for example .nl .es .en get moved by Sickbeard automatically for you?

**Comment by isetz** [comment]
Yes, I do. My subtitles are renamed with the 2 chars language code and moved when the postprocessing is done. But I don't use NZBs so maybe the problem is there.

**Comment by isetz** [comment]
Hmmm but... usually, in fact, my subtitles are downloaded after the episode has been processed because when the download is finished subliminal doesn't find any results. So it could be as you say. We'll try to debug this and find the problem ;)

**Comment by rkuijpers** [comment]
Indeed, it only happens whenever I download older episodes with subtitles available.

New episodes that are downloaded before any subtitles are available, work perfectly, like you say.
Once the episode is moved to its final folder, and subtitles are found, subliminal downloads the subtitle in the final folder.

I discovered this problem as I was downloading dozens of episodes of older series for my daughter.
Built-in Subliminal seems to work faster than Sickbeard in those cases, downloading the subtitles once the download of the episode starts. It looks like Sickbeard doesn't like that at all!

SabToSickBeard script says it fails, and leaves the subtitle in the temporary download folder.
It does move the episode to the final folder though! 

Hope you'll be able to debug and fix it, thanks for looking in to it ;)
