### ISSUE TITLE
Subtitle file persmissions

### ISSUE THREAD

**Issue by odon** [Pistachitos/Sick-Beard#19]
Subtitle files permission are not in line with other files that sickbeard creates.

It seems other files downloaded by sickbeard get proper permissions (see helpers.py ?) but subtitles have their own file permissions rights.

Very annoying, as they didn't get read permission for Others, and I have some remote device accessings files as anonymous.

**Comment by isetz** [comment]
We'll test in dev and merge in master branch later :)

**Comment by odon** [comment]
I'm using dev branch. I'll test tonight. Thank you !

**Comment by odon** [comment]
It does not always work:
- work on post-processing
- work on manual download (CC button)
- does not work on sub backlog

I grepped the code, seems there is a not corrected part in sickbeard/webserve.py:415

**Comment by isetz** [comment]
Thanks I'll check it right now!
