### ISSUE TITLE
Show subtitle history

### ISSUE THREAD

**Issue by Nyaran** [Pistachitos/Sick-Beard#2]
On History page show downloaded subtitles with its provider, language and keywords

**Comment by mr-orange** [comment]
Hi Nyaran I'm working on this feature. Do you have some suggestion to share?

**Comment by mr-orange** [comment]
Just finished, need to test it a little bit but it's seem to work. However no Keywords view on history page.
Made some little changes, also need to ask some question about subtitle handling when you have some times to share.
All the best.
Mr_orange

**Comment by DisasteR** [comment]
Coul'd you add original filename or more information about source file ?
Because when a sub is invalid (bad sync) we have nothing to know which one was taken and wich one to get in replacement.
