### ISSUE TITLE
subtitle downloaded with 600 mask

### ISSUE THREAD

**Issue by lune001** [Pistachitos/Sick-Beard#25]
My subtitle are put in 600 mask so i can't read them from network. Is there a way to change that ?

**Comment by isetz** [comment]
Are you using the master branch? I think it may be related to issue #19 but I thought it was already fixed. Your video file has correct permissions?

**Comment by lune001** [comment]
Yes, i'm using Master branch. All other file related are 664 (mkv/nfo/tbn)
Get the right version of webserve.py ... very strange

2013/4/8 Jud notifications@github.com

**Comment by isetz** [comment]
With my last commit a2a251dd49f00eaa49b09b8a4091c01ad5a5ab9c I think this is finally fixed everywhere. Feel free to reopen if I'm wrong.
