### ISSUE TITLE
Synology Notifier not working

### ISSUE THREAD

**Issue by pvieito** [Pistachitos/Sick-Beard#26]
“Synology Notifier” notifications are not working for me, in the Logs it says:

```
Apr-05 14:51:07 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Script result: synodsmnotify.cpp:153 Fail to send notify to @administrators
Apr-05 14:51:07 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Absolute path to command: /usr/syno/bin/synodsmnotify
Apr-05 14:51:07 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Executing command ['/usr/syno/bin/synodsmnotify', '@administrators', 'Started Download', u'The Simpsons - 23x14 - At Long Last Leave - SD TV']
```

I have been researching and it seems that `sickpirate` user has not privileges to send notifications through `synodsmnotify` (http://forum.synology.com/enu/viewtopic.php?f=27&t=55627).

I tested it on the terminal too:

```
DiskStation> su sickpirate 
/volume1/@appstore/SickBeard-ThePirateBay/var $ synodsmnotify @administrators title text
synodsmnotify.cpp:153 Fail to send notify to @administrators
```

**Comment by isetz** [comment]
Yeah it's true. I had this issue too when we were adding the notification functionality. I've found my post about this problem in the synology forums. Hope that it helps you too http://forum.synology.com/enu/viewtopic.php?f=27&t=55627 If you can't make it work tell me and I try to remember... and provide more help.

**Comment by pvieito** [comment]
I tried to change the permissions of the folder `/usr/syno/etc/preference/admin/` and the file `dsmnotify` but it didn't work. More suggestions?

**Comment by isetz** [comment]
I have the permissions for both `/usr/syno/etc/preference/admin/` and `/usr/syno/etc/preference/@administrators/` set to 770. The owner being admin:users for 'admin' and root:administrators for 'administrators'. Just checking cause I don't remember very well which changes I made apart from permissions...

Let me say that my sickbeard user belongs to the 'users' group. Maybe as they suggested in the synology forums, to make it more secure you could assign another group that is not used by the DSM, but well this will be minor changes after you make it work ;)

**Comment by pvieito** [comment]
I had to change the permissions of all the `administrators` group users, now it's working. Thanks!

**Comment by isetz** [comment]
Great :) You're welcome.
