### ISSUE TITLE
Unable to downloaded anime with development branch

### ISSUE THREAD

**Issue by legatobs** [Pistachitos/Sick-Beard#27]
Love the new layout and I would love to trade in lad1337's branch for this one but I can't seem to download any anime with it.  Tried with Fairy Tail and in the log this is what it said.

Apr-11 19:01:26 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Unable to find a download for Fairy Tail - 174 - Four Dragons
Apr-11 19:01:25 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: Error loading Fanzub URL: https://www.fanzub.com/api?ep=24&limit=100&t=tvsearch&season=4&rid=24288&maxage=1640&cat=5030%2C5040
Apr-11 19:01:25 WARNING  SEARCHQUEUE-MANUAL-SEARCH :: HTTP error 404 while loading URL https://www.fanzub.com/api?ep=24&limit=100&t=tvsearch&season=4&rid=24288&maxage=1640&cat=5030%2C5040
Apr-11 19:01:25 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: Error loading Fanzub URL: https://www.fanzub.com/api?t=tvsearch&cat=5040%2C5030
Apr-11 19:01:25 WARNING  SEARCHQUEUE-MANUAL-SEARCH :: HTTP error 404 while loading URL https://www.fanzub.com/api?t=tvsearch&cat=5040%2C5030

Is this branch able to recognize anime absolute numbering yet or is it still being worked on?
Thanks for the great work you've been doing.

**Comment by Nyaran** [comment]
The problem is probably that Fanzub isn't supported yet
