### ISSUE TITLE
Add support for absolute numbers in post processing

### ISSUE THREAD

**Issue by mythjuha** [Pistachitos/Sick-Beard#28]
Would be nice if you could add absolute numbers to the renaming rules (as done by the lad1337 branch).

**Comment by Nyaran** [comment]
That is done, just check Config > Post processing > Episode Naming
![absolute_naming](https://f.cloud.github.com/assets/1042532/416483/9a6353de-ac4e-11e2-9fb2-3d881ea4d5f8.jpg)

**Comment by mythjuha** [comment]
Odd. I don't seem to have that checkbox even though i just cloned it from github. But so far i'm rly loving it for regular series. Looks awesome, works great!

**Comment by isetz** [comment]
Inside the show, you should go to edit and there you can set absolute
numbering.  In the naming config you can set up specific rename pattern for
animes with absolute numbers
El 23/04/2013 22:04, "mythjuha" notifications@github.com va escriure:

**Comment by mythjuha** [comment]
My bad. Forgot to switch to development branch.

**Comment by isetz** [comment]
Oops ^^
El 23/04/2013 22:37, "mythjuha" notifications@github.com va escriure:

**Comment by mythjuha** [comment]
Then i'd like to reopen the ticket. I was using the following 'naming' in lad1337's version: %SN - %Sx%0E - %0AE - %EN
This seems to be invalid in this version (suppose you can't mix normal and absolute numbers).

Either way, this is looking to be a great alternative!

**Comment by Nyaran** [comment]
Now you can use that pattern
