### ISSUE TITLE
Using both Season numbers and absolute numbers

### ISSUE THREAD

**Issue by mythjuha** [Pistachitos/Sick-Beard#29]
Is it possible to support using both types of numbering at the same time? Currently all my anime is named as 'show - ssxee - abs - title' (%SN - %Sx%0E - %0AE - %EN). I like this because i prefer season numbering, but finding releases is easier if you know the absolute as well. But trying to use this custom format fails with a message 'this pattern is invalid'.

Probably related to my naming, sickbeard pistachitos fails to properly find my episodes.

**Comment by mythjuha** [comment]
I've been diving into the code a little bit, and it seems this is supported by sickbeard\name_parser\regexes.py (although the examples need updating). I believe the regex for this kind that i use is 'anime_and_normal_x'.

**Comment by Nyaran** [comment]
Fixed

**Comment by mythjuha** [comment]
Working nicely, thanks a bunch!
