### ISSUE TITLE
Force download subtitle

### ISSUE THREAD

**Issue by isetz** [Pistachitos/Sick-Beard#3]
Allow forcing manual subtitle download even if they have already been downloaded.

**Comment by isetz** [comment]
Maybe use the downloaded subtitle flag image to launch the forced search of the existing subtitle.

**Comment by Nyaran** [comment]
And to force download subtitles to every episodes of a show, when click on "download subtitles" button, show a popup asking if download missed or download for all episodes

**Comment by mr-orange** [comment]
can it  be done always showing cc button ?

**Comment by Nyaran** [comment]
We think it at first, but.... if you have more than one language enabled and you only want to force download of one language... CC will be to force all languages

**Comment by mr-orange** [comment]
Yep this make sense.
Could you send me you email as private message on the forum?
So we can talk via mail.
Thanks.

Mr_Orange

**Comment by mr-orange** [comment]
About this it can be done if we have a clickable contry flag... What do you think?

**Comment by Nyaran** [comment]
Yes with clickable flag is the best way
