### ISSUE TITLE
Subtitle is not redownloaded when an episode is replaced with a better qualities

### ISSUE THREAD

**Issue by mr-orange** [Pistachitos/Sick-Beard#30]
More than one user are reporting problem on episode subtitle when a better episode qualities is retrived from sickbeard.

**Comment by isetz** [comment]
If the old episode had the subtitles downloaded then even if another version is downloaded it will use the same subtitles previously downloaded. I think this should be added along with the force download subtitles option #3

**Comment by mr-orange** [comment]
Probably have found a solution. Need to be tested.... The solution relies on deleting the subtitles along the video file and resetting the subtitles fields during the post processing.

**Comment by Nyaran** [comment]
Is more easy than that.
https://github.com/Pistachitos/Sick-Beard/commit/d9e697e45676bb13cd428b2b38f9557b49d688e9
I can't check it now, but it should works.

**Comment by mr-orange** [comment]
Thanks Nyaran have added your code to my branch.
I think anyway you have to reset the subtitles field in episode object:

```
            cur_ep.subtitles = []
            cur_ep.subtitles_searchcount = 0
            subtitles_lastsearch = '0001-01-01 00:00:00'
```

or sb subsequent subtitle search will be dirty.
What you think?

**Comment by mr-orange** [comment]
this is the link of my commit based on your code:
https://github.com/mr-orange/Sick-Beard/commit/16a8f063377f1f22666d6f1866d70fbc4210ccf5

**Comment by Nyaran** [comment]
Why reset it? With force option enabled it download subtitles and replace that fields with new values.

**Comment by mr-orange** [comment]
The force option do not repleace the search count field....and this it will
interfere with the db select in find subtitle thread.... where the search
count is a parameter of the select...
Because we are searching subtitle of another video version of the same episode it's better to refresh also those fields.

**Comment by Nyaran** [comment]
Good point, thanks
