### ISSUE TITLE
Use Authentification on Addic7ed to avoid Basic Download Limit

### ISSUE THREAD

**Issue by DisasteR** [Pistachitos/Sick-Beard#31]
Can you add support for authentication on Addic7ed ?

Issue also opened here : https://github.com/Diaoul/subliminal/issues/201

**Comment by isetz** [comment]
LOL DisasteR you went mad with the issues XD. There's a limit for subtitle downloads there?

**Comment by DisasteR** [comment]
yep there is a limit.
- 30 per day for registered users.
- 50 for VIP.

Did not remember for unregistered but certainly less.

I think authentication can be handled with a first POST to get cookie and doing download by reusing it.

**Comment by ducapedia** [comment]
UNregistred is about 5 subtitles...

**Comment by Nyaran** [comment]
This is subliminal stuff
