### ISSUE TITLE
Scene Exceptions Make SB download the proper torrent/nzb, but fail post processing

### ISSUE THREAD

**Issue by mythjuha** [Pistachitos/Sick-Beard#32]
When adding anime shows SB-pista doesn't usually find any releases when using the 'english' name of the anime. I discovered that after adding the japanese name in the scene exceptions list, they are found and downloaded perfectly. However, when post processing the file it also uses the japanese name for searching info from thetvdb, and my guess is that is why post processing fails.

<pre>Processing C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 01 [377BE214].mkv (None)
Parsed [Commie] Hataraku Maou-sama! - 01 [377BE214].mkv into [Commie] Hataraku Maou-sama! - E1 - [377BE214] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 01 [377BE214].mkv into [Commie] Hataraku Maou-sama! - E1 - [377BE214] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed TV [Commie] Hataraku Maou-sama! - 01 [377BE214].mkv into TV [Commie] Hataraku Maou-sama! - E1 - [377BE214] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [Commie] Hataraku Maou-sama!
Looking up TV [Commie] Hataraku Maou-sama! in the DB
Looking up name TV [Commie] Hataraku Maou-sama! on TVDB
Looking up name TV [Commie] Hataraku Maou-sama! in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 01 [377BE214].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 02 [9268D145].mkv (None)
Parsed [Commie] Hataraku Maou-sama! - 02 [9268D145].mkv into [Commie] Hataraku Maou-sama! - E2 - [9268D145] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 02 [9268D145].mkv into [Commie] Hataraku Maou-sama! - E2 - [9268D145] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed TV [Commie] Hataraku Maou-sama! - 02 [9268D145].mkv into TV [Commie] Hataraku Maou-sama! - E2 - [9268D145] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [Commie] Hataraku Maou-sama!
Looking up TV [Commie] Hataraku Maou-sama! in the DB
Looking up name TV [Commie] Hataraku Maou-sama! on TVDB
Looking up name TV [Commie] Hataraku Maou-sama! in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 02 [9268D145].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 03 [485027D8].mkv (None)
Parsed [Commie] Hataraku Maou-sama! - 03 [485027D8].mkv into [Commie] Hataraku Maou-sama! - E3 - [485027D8] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 03 [485027D8].mkv into [Commie] Hataraku Maou-sama! - E3 - [485027D8] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed TV [Commie] Hataraku Maou-sama! - 03 [485027D8].mkv into TV [Commie] Hataraku Maou-sama! - E3 - [485027D8] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [Commie] Hataraku Maou-sama!
Looking up TV [Commie] Hataraku Maou-sama! in the DB
Looking up name TV [Commie] Hataraku Maou-sama! on TVDB
Looking up name TV [Commie] Hataraku Maou-sama! in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 03 [485027D8].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 04 [833070E3].mkv (None)
Parsed [Commie] Hataraku Maou-sama! - 04 [833070E3].mkv into [Commie] Hataraku Maou-sama! - E4 - [833070E3] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 04 [833070E3].mkv into [Commie] Hataraku Maou-sama! - E4 - [833070E3] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed TV [Commie] Hataraku Maou-sama! - 04 [833070E3].mkv into TV [Commie] Hataraku Maou-sama! - E4 - [833070E3] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [Commie] Hataraku Maou-sama!
Looking up TV [Commie] Hataraku Maou-sama! in the DB
Looking up name TV [Commie] Hataraku Maou-sama! on TVDB
Looking up name TV [Commie] Hataraku Maou-sama! in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 04 [833070E3].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 05 [E1E89217].mkv (None)
Parsed [Commie] Hataraku Maou-sama! - 05 [E1E89217].mkv into [Commie] Hataraku Maou-sama! - E5 - [E1E89217] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 05 [E1E89217].mkv into [Commie] Hataraku Maou-sama! - E5 - [E1E89217] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [Commie] Hataraku Maou-sama!
Looking up [Commie] Hataraku Maou-sama! in the DB
Looking up name [Commie] Hataraku Maou-sama! on TVDB
Looking up name [Commie] Hataraku Maou-sama! in all languages on TVDB
Parsed TV [Commie] Hataraku Maou-sama! - 05 [E1E89217].mkv into TV [Commie] Hataraku Maou-sama! - E5 - [E1E89217] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [Commie] Hataraku Maou-sama!
Looking up TV [Commie] Hataraku Maou-sama! in the DB
Looking up name TV [Commie] Hataraku Maou-sama! on TVDB
Looking up name TV [Commie] Hataraku Maou-sama! in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[Commie] Hataraku Maou-sama! - 05 [E1E89217].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 01 [1080p].mkv (None)
Parsed [HorribleSubs] Aku no Hana - 01 [1080p].mkv into [HorribleSubs] Aku no Hana - E1 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 01 [1080p].mkv into [HorribleSubs] Aku no Hana - E1 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed TV [HorribleSubs] Aku no Hana - 01 [1080p].mkv into TV [HorribleSubs] Aku no Hana - E1 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Aku no Hana
Looking up TV [HorribleSubs] Aku no Hana in the DB
Looking up name TV [HorribleSubs] Aku no Hana on TVDB
Looking up name TV [HorribleSubs] Aku no Hana in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 01 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 02 [1080p].mkv (None)
Parsed [HorribleSubs] Aku no Hana - 02 [1080p].mkv into [HorribleSubs] Aku no Hana - E2 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 02 [1080p].mkv into [HorribleSubs] Aku no Hana - E2 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed TV [HorribleSubs] Aku no Hana - 02 [1080p].mkv into TV [HorribleSubs] Aku no Hana - E2 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Aku no Hana
Looking up TV [HorribleSubs] Aku no Hana in the DB
Looking up name TV [HorribleSubs] Aku no Hana on TVDB
Looking up name TV [HorribleSubs] Aku no Hana in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 02 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 03 [1080p].mkv (None)
Parsed [HorribleSubs] Aku no Hana - 03 [1080p].mkv into [HorribleSubs] Aku no Hana - E3 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 03 [1080p].mkv into [HorribleSubs] Aku no Hana - E3 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed TV [HorribleSubs] Aku no Hana - 03 [1080p].mkv into TV [HorribleSubs] Aku no Hana - E3 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Aku no Hana
Looking up TV [HorribleSubs] Aku no Hana in the DB
Looking up name TV [HorribleSubs] Aku no Hana on TVDB
Looking up name TV [HorribleSubs] Aku no Hana in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 03 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 04 [1080p].mkv (None)
Parsed [HorribleSubs] Aku no Hana - 04 [1080p].mkv into [HorribleSubs] Aku no Hana - E4 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 04 [1080p].mkv into [HorribleSubs] Aku no Hana - E4 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed TV [HorribleSubs] Aku no Hana - 04 [1080p].mkv into TV [HorribleSubs] Aku no Hana - E4 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Aku no Hana
Looking up TV [HorribleSubs] Aku no Hana in the DB
Looking up name TV [HorribleSubs] Aku no Hana on TVDB
Looking up name TV [HorribleSubs] Aku no Hana in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 04 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 05 [1080p].mkv (None)
Parsed [HorribleSubs] Aku no Hana - 05 [1080p].mkv into [HorribleSubs] Aku no Hana - E5 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 05 [1080p].mkv into [HorribleSubs] Aku no Hana - E5 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Aku no Hana
Looking up [HorribleSubs] Aku no Hana in the DB
Looking up name [HorribleSubs] Aku no Hana on TVDB
Looking up name [HorribleSubs] Aku no Hana in all languages on TVDB
Parsed TV [HorribleSubs] Aku no Hana - 05 [1080p].mkv into TV [HorribleSubs] Aku no Hana - E5 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Aku no Hana
Looking up TV [HorribleSubs] Aku no Hana in the DB
Looking up name TV [HorribleSubs] Aku no Hana on TVDB
Looking up name TV [HorribleSubs] Aku no Hana in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Aku no Hana - 05 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 01 [1080p].mkv (None)
Parsed [HorribleSubs] Shingeki no Kyojin - 01 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E1 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 01 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E1 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed TV [HorribleSubs] Shingeki no Kyojin - 01 [1080p].mkv into TV [HorribleSubs] Shingeki no Kyojin - E1 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Shingeki no Kyojin
Looking up TV [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name TV [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name TV [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 01 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 02 [1080p].mkv (None)
Parsed [HorribleSubs] Shingeki no Kyojin - 02 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E2 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 02 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E2 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed TV [HorribleSubs] Shingeki no Kyojin - 02 [1080p].mkv into TV [HorribleSubs] Shingeki no Kyojin - E2 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Shingeki no Kyojin
Looking up TV [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name TV [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name TV [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 02 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 03 [1080p].mkv (None)
Parsed [HorribleSubs] Shingeki no Kyojin - 03 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E3 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 03 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E3 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed TV [HorribleSubs] Shingeki no Kyojin - 03 [1080p].mkv into TV [HorribleSubs] Shingeki no Kyojin - E3 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Shingeki no Kyojin
Looking up TV [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name TV [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name TV [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 03 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 04 [1080p].mkv (None)
Parsed [HorribleSubs] Shingeki no Kyojin - 04 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E4 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 04 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E4 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed TV [HorribleSubs] Shingeki no Kyojin - 04 [1080p].mkv into TV [HorribleSubs] Shingeki no Kyojin - E4 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Shingeki no Kyojin
Looking up TV [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name TV [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name TV [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 04 [1080p].mkv:
Processing C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 05 [1080p].mkv (None)
Parsed [HorribleSubs] Shingeki no Kyojin - 05 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E5 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 05 [1080p].mkv into [HorribleSubs] Shingeki no Kyojin - E5 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on [HorribleSubs] Shingeki no Kyojin
Looking up [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Parsed TV [HorribleSubs] Shingeki no Kyojin - 05 [1080p].mkv into TV [HorribleSubs] Shingeki no Kyojin - E5 - [1080p] [ABD: False] [AN: False] [whichReg: ['no_season']]
Checking scene exceptions for a match on TV [HorribleSubs] Shingeki no Kyojin
Looking up TV [HorribleSubs] Shingeki no Kyojin in the DB
Looking up name TV [HorribleSubs] Shingeki no Kyojin on TVDB
Looking up name TV [HorribleSubs] Shingeki no Kyojin in all languages on TVDB
Processing failed for C:\Downloads\Usenet\Complete\TV\[HorribleSubs] Shingeki no Kyojin - 05 [1080p].mkv: </pre>

**Comment by Nyaran** [comment]
Did you enable AniDB options with AniDB account?

**Comment by mythjuha** [comment]
I hadn't. I've added one now but still get the same results when asking to post-process my torrent download folder.

**Comment by mythjuha** [comment]
Been trying to figure out why, and so far i've found that the process method returns false on line 793 (postProcessor.py). I'll try to figure out more later today or tomorrow.

**Comment by mythjuha** [comment]
I pretty much know whats going on, just need some help to fix it. any chance we could talk on IRC or anything?

**Comment by Nyaran** [comment]
I don't have spare time to connect, if you can try to explain the issue
here...

2013/6/26 mythjuha notifications@github.com

**Comment by mythjuha** [comment]
Well, first of all in the file parser.py, line 224 it says: if name.find(showObj.name):
For me, this always returned true. So it tried parsing everything using the first show in my list. I replaced that line with: if showObj.name in name:

This way i was able to move on. However, as the filenames are using the japanese name of the anime, it never did find any match. So the 2nd part of the code is ran. As it doesn't yet know what show the file belongs to, it uses ALL REGEX, and for example '[HorribleSubs] Aku no Hana - 02 [1080p].mkv' seems to match the NORMAL regex 'no season'. After parsing the filename using that regex, it thinks the showname is '[HorribleSubs] Aku no Hana', with the releasegroup as part of it.

**Comment by Nyaran** [comment]
"find" method returns -1 when fails and -1 is true as boolean, my mistake, thanks

After that, it can know if the show is anime, because, "Aku no Hana" is in "[HorribleSubs] Aku no Hana", then, it knows the show, then can use the correct regex

**Comment by mythjuha** [comment]
It doesn't, as the show is known in sickneard as flowers of evil

**Comment by Nyaran** [comment]
Just add Aku no Hana as Scene Exception =)

**Comment by mythjuha** [comment]
Working now :), thanks!
