### ISSUE TITLE
Log original subtitle name.

### ISSUE THREAD

**Issue by DisasteR** [Pistachitos/Sick-Beard#35]
Coul'd you add original filename or more information about source file ?
Because when a sub is invalid (bad sync) we have nothing to know which one was taken and wich one to get in replacement.

**Comment by Nyaran** [comment]
Update your SB. Now you can see it on resource column (if name is too long, move mouse over it to show complete text)

**Comment by DisasteR** [comment]
error on history page : 
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/Sick-Beard_Pistachitos/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/opt/Sick-Beard_Pistachitos/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/opt/Sick-Beard_Pistachitos/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/Sick-Beard_Pistachitos/sickbeard/webserve.py", line 752, in index
    return _munge(t)
  File "/opt/Sick-Beard_Pistachitos/sickbeard/webserve.py", line 127, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "/usr/lib/pymodules/python2.6/Cheetah/Template.py", line 981, in __str__
    def **str**(self): return getattr(self, mainMethName)()
  File "_opt_Sick_Beard_Pistachitos_gui_slick_interfaces_default_history_tmpl.py", line 189, in respond
NameError: global name 'episode' is not defined

**Comment by Nyaran** [comment]
Copy-Paste mistake, fixed

**Comment by DisasteR** [comment]
just saw your commit :) about removing absolute numbering for anime.

hum ... in the ressources column i actually have the actual filename on my disk.

did it only show the original (from site where dowloaded) for the next ones ?

**Comment by Nyaran** [comment]
Oh crap, I see, hmmm, I'm not sure if actually we can get original filename

**Comment by DisasteR** [comment]
yep cause now we have a colum with the same content than the overlay on "action" column not really usefull :p

and didn't help for sub download error :/

hope you found a solution :)

**Comment by Nyaran** [comment]
lol I didn't know that if you overlay on action column you can see that hahaha ^^"

**Comment by Nyaran** [comment]
I try with Subtitulos.es and OpenSubtitles, and file doesn't have a name for each version, when you download a subtitle always have the same name, independently of version. Ej: "Castle 5x18 - The Wild Rover (Español (España)).srt"

Then I can't do anything for this >_<

**Comment by DisasteR** [comment]
when i have worked with periscope on my own fork i have used the object sub['release'] returned by the periscope listSubtitles() function. there is not equivalent of this for subliminal ?

Have a look here : 
https://github.com/DisasteR/Sick-Beard/blob/master/sickbeard/webserve.py#L2650

**Comment by DisasteR** [comment]
sickbeard downloadSubtitles() use subliminal.download_subtitles() who return : 
:return: downloaded subtitles
:rtype: dict of :class:`~subliminal.videos.Video` => [:class:`~subliminal.subtitles.ResultSubtitle`]

the dict is build with ResultSubtitle() object defined in lib/subliminal/subtitles.py with this params : 
    :param string path: path to the subtitle
    :param language: language of the subtitle
    :type language: :class:`~subliminal.language.Language`
    :param string service: name of the service
    :param string link: download link for the subtitle
    :param string release: release name of the video
    :param float confidence: confidence that the subtitle matches the video according to the service
    :param set keywords: keywords that describe the subtitle

Maybe the release param here is the same as the one in periscope ..?

Could you have a try ?

**Comment by Nyaran** [comment]
I will try to check when I back home
