### ISSUE TITLE
Season folders

### ISSUE THREAD

**Issue by mythjuha** [Pistachitos/Sick-Beard#36]
I have my anime renaming configured as:

<pre>Season %0S/%SN - %0Sx%0E - %0AE - %EN</pre>

The sample below shows:

<pre>Season 02\Show Name - 02x03 - 073 - Ep Name.ext</pre>

Yet when downloading a new episode, and post processing succeeds, it gets placed in a folder without the season folder:

<pre>Found release name [yibis]_One_Piece_593_[720p][4A445781]
Destination folder for this episode: D:\Anime\One Piece
Adding the file to the anidb mylist
Copying file from C:\Downloads\Torrents\Torrents\[yibis]_One_Piece_593_[720p][4A445781].mkv to D:\Anime\One Piece\One Piece - 16x14 - 593 - Save Nami! Luffy's Snow Mountain Battle.mkv
Processing succeeded for C:\Downloads\Torrents\Torrents\[yibis]_One_Piece_593_[720p][4A445781].mkv</pre>

I know i've been making quite a few 'issues', but thats only because I believe that this version of sickbeard is worth replacing lad1337's one. There's just some things that used to work in lad's and aren't yet working correctly (for me) in this one.

**Comment by Nyaran** [comment]
Don't worry about sending a lot of issues, we know this isn't perfect, and we want to fix all bugs (when spare time allow us).

I will try to fix it soon as posible ;)

**Comment by mythjuha** [comment]
Also, if needed i might be able to help out as well. I have quite a bit of programming experience (i work as a .net developer for industry automation software), but not in python. Still, with a bit of guidance on the IDE used, and the structure of sickbeard I should be able to help identify problems.

**Comment by Nyaran** [comment]
For develop we use Eclipse with PyDev plugin.

All help are always welcome =)

**Comment by mythjuha** [comment]
Post processing fails. I believe it's related to this issue still. I still use the same naming as above.

Here's some debug info:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

[code]Traceback (most recent call last):
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\cherrypy_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\cherrypy\lib\encoding.py", line 193, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\cherrypy_cpdispatch.py", line 25, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\sickbeard\webserve.py", line 2096, in processEpisode
    result = processTV.processDir(dir, nzbName)
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\sickbeard\processTV.py", line 93, in processDir
    returnStr += processDir(ek.ek(os.path.join, dirName, curFolder), recurse=True)
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\sickbeard\processTV.py", line 108, in processDir
    process_result = processor.process()
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\sickbeard\postProcessor.py", line 890, in process
    proper_path = ep_obj.proper_path()
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\sickbeard\tv.py", line 2011, in proper_path
    def proper_path(self):
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\sickbeard\tv.py", line 2072, in formatted_filename
    pattern = sickbeard.NAMING_PATTERN
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\sickbeard\tv.py", line 1896, in _format_pattern
    pattern = sickbeard.NAMING_PATTERN
  File "C:\Users\Myth\Documents\GitHub\Sick-Beard\sickbeard\tv.py", line 1842, in _replace_map
KeyError: 3
[/code]

**Comment by Nyaran** [comment]
My line 1842 of file tv.py is only a break line. What do you have there??

**Comment by mythjuha** [comment]
I'm not at home to verify, but if i remember correctly it was also a break line, just before a return statement mapping the different naming types to their values (%E, %S, etc ...). I also found this odd, but as i'm not familiar with IDLE or aptana debugging i figured this might be normal and meaning the 'next not empty line'. 

Seeiing how there was also a KeyError: 3, i supposed this meant index 3 of that return array.

**Comment by mythjuha** [comment]
Ok, the exceptions were probably due to old compiled python files. I restarted the application and it's now not giving me any hard exceptions, however I still get the same results at I posted at the beginning of issue 32 (https://github.com/Pistachitos/Sick-Beard/issues/32). To make sure I hadn't changed anything i did a 'git rest --hard'. I'll see if i can do some debugging myself.

**Comment by mythjuha** [comment]
This issue can be closed as it's working. It was reopened based on wrong information.
