### ISSUE TITLE
English only for nyaatorrents provider 

### ISSUE THREAD

**Issue by e6719039** [Pistachitos/Sick-Beard#37]
When using the nyaatorrent provider you don't know what language is the episode going to be downloaded, I have had episodes dled in french a couple of times.

When searching in the nyaa site there's a "english translated" option, could that be included as an English only provider?

**Comment by Nyaran** [comment]
Config > Search Providers
Select 'Configure Built-In Providers' tab
Select 'NyaaTorrents' on combobox
Select a category and/or a filter

=)
