### ISSUE TITLE
Opensubtitles doesnt download any subtitles in PT-BR

### ISSUE THREAD

**Issue by ducapedia** [Pistachitos/Sick-Beard#38]
I tried "-l pt-br", "-l pob-BR" but never download when I'm using "-s opensubtitles"
without specifying the server plugin, mostly of times it downloads from addic7ed. (bjork isn't woking too... it complains about missing 'xml', when its already installed.

**Comment by isetz** [comment]
Have you addressed to Diaoul in https://github.com/Diaoul/subliminal about this issue?

**Comment by Nyaran** [comment]
Are you using it with commands??? This isn't a subliminal fork, is a project that integrates subliminal. To use subliminal and report problems go to https://github.com/Diaoul/subliminal as Isetz said.
