### ISSUE TITLE
Unable to find your git executable

### ISSUE THREAD

**Issue by mythjuha** [Pistachitos/Sick-Beard#39]
Lately I been getting the following message on top:
Unable to find your git executable - either delete your .git folder and run from source OR set git_path in your config.ini to enable updates.

It's been a while now but haven't been paying much attention to it. I haven't been changing the config.ini file so i guess it snuck in during an update?

**Comment by isetz** [comment]
This happens to me when I've changed something in SB files so when it tries
to make the pull request there is some kind of conflict. Have you changed
sth?

**Comment by mythjuha** [comment]
Not willingly anyhow. I did install aptana and load sick beard with it to try and see if i could make some sence out of the program to help debug some of my issues. Perhaps i accidentally added an enter or something. I'll have a look if i can revert any changes or something.

**Comment by mythjuha** [comment]
Seems like I indeed changed a file. I've checked it out again now but the message is still there.

**Comment by isetz** [comment]
The times this has happened to me I just downloaded the original file and replaced, then the pull worked. Or just download all SB files and overwrite yours.

**Comment by Nyaran** [comment]
Try this:
Turn off your SB
On config file, find the property git_path, and set it to the path where your git was installed. (I don't remember if you need to set to git directory, bin directory inside git or git executable, xD)
Turn on you SB

**Comment by mythjuha** [comment]
Figured it out. I'm running SB on a windows server and have it configured to start sickbeard at login, but using the system account (so it does not show the console windows). However the system account did not have the git path configured in it's environmont variables.
