### ISSUE TITLE
Select when to use Torrent.

### ISSUE THREAD

**Issue by DisasteR** [Pistachitos/Sick-Beard#41]
Hi,

Could you add the possibility to configure when to use torrent per type of download ?

ex:
TV Show : Use "NZB + Torrent" / "NZB Only" / "Torrent Only"
Anime : Use "NZB + Torrent" / "NZB Only" / "Torrent Only"

And allow to select priority when using "NZB + Torrent" mode.

thanks,

**Comment by Nyaran** [comment]
Isn't a bad idea, we can study that =)

**Comment by isetz** [comment]
Right now we are analising the option of a "sickbeard remake" so we are going to stop implementing further enhancements. Only fixing critical issues.
