### ISSUE TITLE
Add to post-process - unrar 

### ISSUE THREAD

**Issue by piotrasd** [Pistachitos/Sick-Beard#43]
Hi
Nice will be finly add unrar option to post-process 

i saw even to couchpotato unrar come...
https://github.com/mano3m/CouchPotatoServer/commit/f43d8fba9e5da1f18d4197163865b4f8c62f17aa

i hope soon also will be in sickbeard, thanks

**Comment by Nyaran** [comment]
Probably we add this option in the future, but while we implement it, I am sure that your torrent client can extract files  when download ends

**Comment by piotrasd** [comment]
yes, when im manual add some post-script anyway (transmission)
other clints also most need add something (some scripts etc)

most easy was add this from sickbeard side (then this not will be depend of torrent client)

**Comment by isetz** [comment]
Right now we are analising the option of a "sickbeard remake" so we are going to stop implementing further enhancements. Only fixing critical issues.
