### ISSUE TITLE
View log in browser = memory error, log is huge, > 3 Gb and not rotating anymore

### ISSUE THREAD

**Issue by rkuijpers** [Pistachitos/Sick-Beard#44]
Since last update I get the following error when viewing log in Sickbeard:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Sickbeard\cherrypy_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "C:\Sickbeard\cherrypy\lib\encoding.py", line 193, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Sickbeard\cherrypy_cpdispatch.py", line 25, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Sickbeard\sickbeard\webserve.py", line 2510, in viewlog
    data = f.readlines()
MemoryError

Powered by CherryPy 3.2.0rc1 

When looking at the log directory, the log is huge, > 3 Gb and isn't rotating anymore. Any ideas on how to solve this?
I can delete the logfile manually after shutting down Sickbeard.

Restart doesn't help.

**Comment by Nyaran** [comment]
O_o
3GB of log?? that is odd

Try to delete and start SB, then look it file size. Then do some other actions (full update, add show, force backlog, etc) and check always the file size, If one of that action generates ~3GB of log file we can check that

Pd. How many shows have you registered?

**Comment by rkuijpers** [comment]
On the added printscreen you can see the size of the logfile, without touching it there was about 500 Mb added to it in 10-12 hours time. It was now 4Gb in size.

![printscreen](https://f.cloud.github.com/assets/3390020/979043/4a43ca38-06d4-11e3-8f46-fae52b8dd30e.gif)

90 shows (78 active) | 886/2123 episodes downloaded | Search: 0:12:50 | Backlog: wo aug 21

I restarted Sickbeard aftr deleting the logfile, and without actions the (new) log grew to 9.018 Kb. 
Log looks healthy, no errors.
I did a mass update on all shows, and watched the log grow to 9.757 Kb and wooow, the rotating of logs works this time! This is what is supposed to happen every time:

![printscreen2](https://f.cloud.github.com/assets/3390020/979057/595a2eb6-06d6-11e3-9c89-457b750e971c.gif)

Very strange, I already deleted the huge log a few times after shutting down Sickbeard over the last few weeks, and each time it kept growing into Gb's after a restart.

After doing all kinds of actions within Sickbeard the log looks like this now:

![printscreen3](https://f.cloud.github.com/assets/3390020/979076/dd77cc5c-06d7-11e3-88cd-3df6b6e804b9.gif)

Looks like the problem solved itself for now... I'm just glad I made a printscreen of the huge log, or else I wouldn't have believed it myself. I guess I'll close this thread now, sorry for bothering you!

Thanks for your help Nyaran, it's greatly appreciated! ;-)
