### ISSUE TITLE
PublicHD

### ISSUE THREAD

**Issue by ghost** [Pistachitos/Sick-Beard#46]
When is PublicHD going to be implemented?
Also another one: https://yify-torrents.com/

At https://github.com/bricky/Sick-Beard there is already PublicHD implemented.

**Comment by isetz** [comment]
You are talking about a fork with some interesting stuff added, maybe we can take a look and add some of those functionalities to our branch.

**Comment by ghost** [comment]
That would be very cool to make this fork better! :-)

**Comment by isetz** [comment]
Right now we are analising the option of a "sickbeard remake" so we are going to stop implementing further enhancements. Only fixing critical issues.

**Comment by ghost** [comment]
Cool! Goodluck with it isetz! :)
