### ISSUE TITLE
Not creating Season Folders

### ISSUE THREAD

**Issue by niksnation** [Pistachitos/Sick-Beard#47]
SB doesn't seem to create season folders so when I try to Post-Process it fails to move file because the season folder doesn't exist.
any help would be greatly appreciated

**Comment by isetz** [comment]
That's weird. I don't use season folders myself but I think we have not made any modifications on this matter, maybe on the anime changes... have you tried to do a full update of the shows, to check if the folders are created?

**Comment by Nyaran** [comment]
I use seasons folders and I don't have any problem..
A week ago, I added new show and season folders was created without any problem. Check your file name pattern.

**Comment by niksnation** [comment]
I have Flatten Folders unchecked. i have a custom naming pattern "\Season %0S\%SN - S%0SE%0E - %EN". 
But get this error when i at least try to do a manual PostProcess: 
Unable to move file /volume1/Downloads/[ www.Torrenting.com ] - The.Blacklist.S01E03.HDTV.x264-LOL/the.blacklist.103.hdtv-lol.mp4 to /Season 01/The Blacklist - S01E03 - Wujing.mp4: [Errno 2] No such file or directory: '/Season 01/The Blacklist - S01E03 - Wujing.mp4'
Processing failed for /volume1/Downloads/[ www.Torrenting.com ] - The.Blacklist.S01E03.HDTV.x264-LOL/the.blacklist.103.hdtv-lol.mp4: Unable to move the files to their new home.

i assume thats why it wont automattically post-process as well.

**Comment by niksnation** [comment]
I seem to have fixed it for the most part by adding the full path in the episode naming (which is custom) in Post-Processing. 
I did change the config file to "create_missing_show_dirs = 1" 
it still doesnt create all season folders but at least make a new one when trying to write to it
However now I am receiving an error when moving just one file:

Looking up quality for name the.colbert.report.2013.10.07.james.spithill..hdtv.x264-2hd.mp4, got SD TV
Is ep a priority download: False
There is no existing file so there's no worries about replacing it
Destination folder for this episode: /volume1/video/TV/The Colbert Report/Season 10
Moving file from /volume1/Downloads/the.colbert.report.2013.10.07.james.spithill..hdtv.x264-2hd.mp4 to /volume1/video/TV/The Colbert Report/Season 10/The Colbert Report - S10E05 - James Spithill.mp4
Unable to move file /volume1/Downloads/the.colbert.report.2013.10.07.james.spithill..hdtv.x264-2hd.mp4 to /volume1/video/TV/The Colbert Report/Season 10/The Colbert Report - S10E05 - James Spithill.mp4: [Errno 13] Permission denied: '/volume1/video/TV/The Colbert Report/Season 10/The Colbert Report - S10E05 - James Spithill.mp4'
Processing failed for /volume1/Downloads/the.colbert.report.2013.10.07.james.spithill..hdtv.x264-2hd.mp4: Unable to move the files to their new home.

Shouldn't have any permission problems as it moved other shows fine.

**Comment by niksnation** [comment]
Looks like it was just a permissions issue. everything is looking good now. Love your work.
