### ISSUE TITLE
Subtitle download error ?

### ISSUE THREAD

**Issue by DisasteR** [Pistachitos/Sick-Beard#6]
I think the selection process on Addic7ed isn't right.

example for merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov
the sub dowloaded is http://www.addic7ed.com//updated/1/67759/1.

Corresponding to "Version Proper.TLA" Most updated.

09:31:14 INFO::Consuming ListTask(Episode(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.mkv), language_set([Language(French), Language(English)]), opensubtitles, ServiceConfig(True, /opt/Sick-Beard-Pistachos/cache, None))
09:31:14 DEBUG::Initializing OpenSubtitles
09:31:14 DEBUG::Getting subtitles [{'moviebytesize': '964969098', 'sublanguageid': 'fre,eng', 'moviehash': 'a62188e1b7244304'}] with token d48t1u1s023ifoovn5e88d3em6
09:31:14 DEBUG::Terminating OpenSubtitles
09:31:14 DEBUG::Terminating Addic7ed
09:31:14 DEBUG::Cache: saving cache to /opt/Sick-Beard-Pistachos/cache/subliminal_Addic7ed.cache
09:31:14 DEBUG::Video keywords set([u'h264', u'hdtv', u'720p']) - Subtitle keywords set([u'xvid', u'fov', u'hdtv'])
09:31:14 DEBUG::Found {'keywords': 1, 'series': 1, 'episode': 1, 'season': 1}
09:31:14 INFO::Computed confidence 0.9661 for Episode(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.mkv) and ResultSubtitle(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.en.srt, English, opensubtitles, 1.00, release=Merlin.2008.S05E02.HDTV.XviD-FoV.srt)
09:31:14 DEBUG::Created task DownloadTask(Episode(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.mkv), [ResultSubtitle(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.en.srt, English, addic7ed, 1.00), ResultSubtitle(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.en.srt, English, opensubtitles, 1.00, release=Merlin.2008.S05E02.HDTV.XviD-FoV.srt)])
09:31:14 INFO::Consuming DownloadTask(Episode(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.mkv), [ResultSubtitle(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.en.srt, English, addic7ed, 1.00), ResultSubtitle(/home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.en.srt, English, opensubtitles, 1.00, release=Merlin.2008.S05E02.HDTV.XviD-FoV.srt)])
09:31:14 DEBUG::Initializing Addic7ed
09:31:14 INFO::Downloading http://www.addic7ed.com//updated/1/67759/1 in /home/disaster/Videos/TV/Merlin/merlin_2008.5x02.arthurs_bane_part_two.repack.720p_hdtv_x264-fov.en.srt
09:31:14 DEBUG::Download finished
09:31:14 DEBUG::Terminating Addic7ed
09:31:14 DEBUG::CP Server Thread-4 :: 83123: Downloaded English subtitles for episode 5x2

**Comment by DisasteR** [comment]
also the french sub isn,t downloaded...
notice that the Version TLA have an french sub.
here is the episode page on addicted http://www.addic7ed.com/serie/Merlin/5/2/Arthur's_Bane

There is sub in english for the "Repack.720p.FoV" version

Like is said on Addi7ed : " _LOL & SYS always work with 720p DIMENSION; XII & ASAP always work with 720p IMMERSE; 2HD always works with 720p 2HD; BiA always works with 720p BiA; **FoV always works with 720p FoV**_ "

And we have french subs for the normal version and repack.

**Comment by isetz** [comment]
Hi DisasteR, I see the problem... but this isn't really caused by the last changes made in the Addic7ed script. In fact, what I've changed was only related to adding the custom keywords. The issue that you are reporting now occurs when the script opens the series page and selects one of the avaliable subtitles. 

Maybe this should be reported in subliminal master branch. I'm sure Diaoul has more knowledge about the subtitle search process and may help. 

About that "comment" that says: "LOL & SYS always work with 720p DIMENSION; XII & ASAP always work with 720p IMMERSE; 2HD always works with 720p 2HD; BiA always works with 720p BiA; FoV always works with 720p FoV ", I don't think the search script uses it at all.

**Comment by DisasteR** [comment]
i look at the Diaoul open issues for subliminal and i found this one https://github.com/Diaoul/subliminal/issues/146
I have tried to add FOV to the releaseGroup list in guessit/pattern.py file and all the sub where downloaded correctly.

wackou (GuessIt dev) have updated guessit and forked subliminal. maybe you can take a look at his work.

and add FOV to the releaseGroup list.

**Comment by isetz** [comment]
I'll take a look :+1:

**Comment by DisasteR** [comment]
Maybe the group list can be updated with some of the TV groups from this site : http://scenegrouplist.com/lists.php

**Comment by DisasteR** [comment]
some information about this closing ? have you made some change ?

**Comment by isetz** [comment]
Nope, this is not resolved, just a confusion :P. I'm a bit out of time right now but maybe we can check that subliminal branch you talked about.

**Comment by Nyaran** [comment]
I thought this was fixed, sorry :P

**Comment by isetz** [comment]
I was thinking...  DisasteR maybe the solution could be just asking wackou to update patterns.py releaseGroup list?

**Comment by DisasteR** [comment]
I have oppened the issue https://github.com/wackou/guessit/issues/26

**Comment by isetz** [comment]
Great :)

**Comment by DisasteR** [comment]
Fixed by Wackou for group FoV !

**Comment by isetz** [comment]
Awesome ^^
