### ISSUE TITLE
Per show Ignore word + ( required word and show title TAG sb+metadata )

### ISSUE THREAD

**Issue by DisasteR** [Pistachitos/Sick-Beard#7]
It can be interesting to have a per show ignore list.

also can you add a per show required word ?
- **why the required words ?**

I whant to have two versions of the same show.
- One in english.
- One in french. _for this one i have to add FRENCH as a required word._
- **why the title tag/renaming ?**

Two allow my xbmc to handle the two show separatly
ex : 
- Merlin - EN
- Merlin - FR

**Comment by DisasteR** [comment]
I have made some test and XBMC only need different folder name for the show and different `<title>` in the tvshow.nfo
to handle them separatly.

Here is my test setup :
Folders :
tvshow - EN
tvshow - FR

title in tvshow.nfo was modified to add " -  EN" and " -  FR"

**Comment by DisasteR** [comment]
some new about that request ?
at least could you add the per show Ignored/Required words ?

**Comment by isetz** [comment]
I don't think this is a priority, although we've not been working at all this past days since it's been xmas holidays :)

About the ignored/required words per show, I think Nyaran was working on it.

**Comment by DisasteR** [comment]
I just wanted to bump the thread and have some news :)
Hope you all have passed good holidays.

Hppy to learn that Nyaran is working on it :+1: 

Wish you an happy new year :)

**Comment by isetz** [comment]
I wish you a happy new year too ;)

**Comment by Nyaran** [comment]
Right know I am working on the anime branch and the other issues have been delayed

P.S. Happy new year =)

**Comment by DisasteR** [comment]
Ok :)

Hope you will start working on this shortly :p

**Comment by DisasteR** [comment]
any news ? :)

**Comment by DisasteR** [comment]
Hi,

Have you some news about this ?

The required word will be very usefull for anime to download only vostfr.

Regards,

**Comment by Nyaran** [comment]
Is on queue list ;)

**Comment by isetz** [comment]
Right now we are analising the option of a "sickbeard remake" so we are going to stop implementing further enhancements. Only fixing critical issues.

**Comment by DisasteR** [comment]
good :)
I hope this request appear in the features list :p 
keep us in touch of the "remake" :)
