### ISSUE TITLE
Web UI corrupted when adding a show

### ISSUE THREAD

**Issue by MartinAyla** [Pistachitos/Sick-Beard#9]
Hi

I'm trying to add a TV show and the web UI looks like this (and I can't click the Next button):

![Screen Shot 2012-12-18 at 15 00 14](https://f.cloud.github.com/assets/3063746/19459/755bf582-491b-11e2-9464-74fefffc2ebb.png)

**Comment by Nyaran** [comment]
OMG xD
Temp fix: Change to Step 2 and back to Step 1

**Comment by MartinAyla** [comment]
Clicking on "Step 2" and then on "Step 1" works for now :)

Thanks again Nyaran, really appreciate the fast replies and help!

**Comment by Nyaran** [comment]
Fixed, update your SB
